### ISSUE TITLE
yolofastestv2 Pytorch to onnx

### ISSUE THREAD

**Issue by danielzhangau** [LiQiang0307/yoloFastestV2-OpenVINO#1]
Hi there, I am having trouble with converting yolofastestv2 model from pytorch to onnx
More problem detail is on: hpc203/yolo-fastestv2-opencv#1 (comment)
Any helps will be appreciated!!

### Cause identification:

`yolofastestv2` 源代码里输出2个尺度特征图的，`yolofastestv2-opencv` version在转换`onnx`文件的程序里做了一个`torch.cat`的处理，把两个输出特征图拼接成一个

My understanding is the model output is two different scale of feature maps, but the `OpenCV` version implementation only accept one. How to concatenate two features maps when converting the format from `PyTorch` to `onnx`?

**Comment by LiQiang0307** [comment]
> Hi there, I am having trouble with converting yolofastestv2 model from pytorch to onnx More problem detail is on: [hpc203/yolo-fastestv2-opencv#1](https://github.com/hpc203/yolo-fastestv2-opencv/issues/1) (comment) Any helps will be appreciated!!
> 
> ### Cause identification:
> `yolofastestv2` 源代码里输出2个尺度特征图的，`yolofastestv2-opencv` version在转换`onnx`文件的程序里做了一个`torch.cat`的处理，把两个输出特征图拼接成一个
> 
> My understanding is the model output is two different scale of feature maps, but the `OpenCV` version implementation only accept one. How to concatenate two features maps when converting the format from `PyTorch` to `onnx`?

![image](https://user-images.githubusercontent.com/44935269/143405034-cf3ff6aa-9895-4c9c-b83e-ffbe2b01b025.png)

**Comment by LiQiang0307** [comment]
> Hi there, I am having trouble with converting yolofastestv2 model from pytorch to onnx More problem detail is on: [hpc203/yolo-fastestv2-opencv#1](https://github.com/hpc203/yolo-fastestv2-opencv/issues/1) (comment) Any helps will be appreciated!!
> 
> ### Cause identification:
> `yolofastestv2` 源代码里输出2个尺度特征图的，`yolofastestv2-opencv` version在转换`onnx`文件的程序里做了一个`torch.cat`的处理，把两个输出特征图拼接成一个
> 
> My understanding is the model output is two different scale of feature maps, but the `OpenCV` version implementation only accept one. How to concatenate two features maps when converting the format from `PyTorch` to `onnx`?

推荐一个模型可视化软件：https://github.com/lutzroeder/netron
通过打开https://github.com/hpc203/yolo-fastestv2-opencv  中的model.onnx 可以看出模型的concat操作，如图所示。

torch.Size([1, 22, 22, 95]) torch.Size([1, 11, 11, 95])

【1x22x22 ，95】   【1x11x11,95】
【484+121，95】

代码稍后给出！

**Comment by danielzhangau** [comment]
好的！谢谢！可视化之后清楚了很多！

**Comment by danielzhangau** [comment]
> > Hi there, I am having trouble with converting yolofastestv2 model from pytorch to onnx More problem detail is on: [hpc203/yolo-fastestv2-opencv#1](https://github.com/hpc203/yolo-fastestv2-opencv/issues/1) (comment) Any helps will be appreciated!!
> > ### Cause identification:
> > `yolofastestv2` 源代码里输出2个尺度特征图的，`yolofastestv2-opencv` version在转换`onnx`文件的程序里做了一个`torch.cat`的处理，把两个输出特征图拼接成一个
> > My understanding is the model output is two different scale of feature maps, but the `OpenCV` version implementation only accept one. How to concatenate two features maps when converting the format from `PyTorch` to `onnx`?
> 
> 推荐一个模型可视化软件：https://github.com/lutzroeder/netron 通过打开https://github.com/hpc203/yolo-fastestv2-opencv 中的model.onnx 可以看出模型的concat操作，如图所示。
> 
> torch.Size([1, 22, 22, 95]) torch.Size([1, 11, 11, 95])
> 
> 【1x22x22 ，95】 【1x11x11,95】 【484+121，95】
> 
> 代码稍后给出！

哈喽， 多谢你的指导，我解决了这个issue！代码我新建了一个pull request，可以参考看看！
https://github.com/LiQiang0307/yoloFastestV2-OpenVINO/pull/2#issue-1064115850
